import { NextPage } from 'next';
import Head from 'next/head';

import Table from '../../../components/Table';
import Footer from '../../../components/Footer';

import styles from '../../../styles/Home.module.css';

const Paths: NextPage = () => {
  const CONTENTS = [
    { number: '1', name: 'bulbasaur' },
    { number: '2', name: 'ivysaur' },
    { number: '3', name: 'venusaur' },
    { number: '4', name: 'charmander' },
    { number: '5', name: 'charmeleon' },
    { number: '5', name: 'charizard' },
  ];

  return (
    <div>
      <Head>
        <title>getServerSideProps</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h2>This page is used by getStaticPaths 😜</h2>

        <p className={styles.description}>
          This is page in
          <code className={styles.code}>pages/static/paths/index.tsx</code>
        </p>

        <p>
          If a page has dynamic routes and uses getStaticProps
          <br />
          it needs to define a list of paths that have to be rendered to HTML at build time.
        </p>

        <Table tableContents={CONTENTS} alias='paths' />
        <p>It has only 3 static paths.</p>
      </main>

      <Footer />
    </div>
  );
};

export default Paths;
