import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Footer from '../components/Footer';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js!</h1>

        <p className={styles.description}>
          This is page in
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>🤓</h2>
            <p>Only allowed in a page</p>
          </div>

          <Link href='/static/props'>
            <a className={styles.card}>
              <h2>getStaticProps</h2>
              <p>For static routes</p>
            </a>
          </Link>

          <Link href='/static/paths'>
            <a className={styles.card}>
              <h2>getStaticPaths</h2>
              <p>For static dynamic routes</p>
            </a>
          </Link>

          <Link href='/ssr'>
            <a className={styles.card}>
              <h2>getServerSideProps</h2>
              <p>For SSR</p>
            </a>
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
